### ISSUE TITLE
Is torara LMS open or close source?

### ISSUE THREAD

**Issue by wlnirvana** [totara/totara-docker-dev#101]
**Describe the bug**

Different sources from the official website seem to conflict with each other regarding the open source policy of torara.

**To Reproduce**

1. Visit [this page from the official web site][1], which says totara learn lms is open sourced.
2. Visit [this official getting code page][2], which says only parters and subscribers can access the code.

**Expected behavior**

The open source policy should be clear and consistent.

[1]:https://www.totaralearning.com/en/products/totara-learn-lms
[2]:https://help.totaralearning.com/display/DEV/Getting+the+code

**Comment by simoncoggins** [comment]
This is the wrong place for this question as this issue tracker is for reporting bugs with the Totara's docker setup.

To answer your question, this article from our CEO outlines our position:

https://opensource.com/article/17/8/software-freedom

If you have any further questions you can email them to licensing@totaralearning.com.
