### ISSUE TITLE
Set tdb backup directory in .env

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#110]
At the moment you have to specify the full backup path on your local filesystem for where you want to backup/restore from for the ```tdb``` command if you have a custom backup name. (E.g ```tdb restore totara13 ~/tdb_backups/1000_users.pgsql11```)

This is a little inconvenient, as in most cases you probably wouldn't have multiple different directories for your backups. Really we should just make it so you set a variable like ```TDB_BACKUP_DIR=/path/to/backup/dir``` in the ```.env``` file, and then you could just go something like: ```tdb restore totara13 1000users.pgsql11```

**Comment by derschatta** [comment]
resolved by #119
