### ISSUE TITLE
Fix file permissions issues when running commands inside containers

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#116]
If you run a command such as ```git checkout integration/t13-release``` whilst inside a container, then the correct permissions will not be applied to the affected files. This can get annoying - especially with files such as the tui build files which are build using the ```tnpm``` command - as you aren't able to edit or delete them on your host machine's file system.

To fix this, we need to make sure the correct UID and GID values are passed to the php and nodejs containers so that when they run the commands, the run it as the same user as the host machine (ie you). This is done by adding ```user: "${UID}:${GID}"``` to each container compose yml entry.

**Comment by derschatta** [comment]
Never had that problem. When do you run git commands from within the container? Wouldn't you just run the git commands from your host? On Mac we don't even sync the git folder to the containers as it's not necessary.

**Comment by markmetcalfe** [comment]
Git isn't a huge problem as like you said you can just run the command outside of the container. However the ```tnpm``` command is problematic (on Ubuntu at least) as it sets different permissions for the build files which means you can't edit or delete them without running ```sudo chmod``` which becomes annoying

**Comment by derschatta** [comment]
tried this but did get totally strange results when using the containers. I don't think on Mac OS it's that easy.

**Comment by derschatta** [comment]
I think you would need the same user / group as the docker host within the docker container for this to work.

**Comment by derschatta** [comment]
https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf

is a good read

**Comment by derschatta** [comment]
This did not come up anymore. Closing and can be reopened if someone else reports it.
