### ISSUE TITLE
Add multiple site support to tbash/tzsh commands

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#117]
Currently if you run ```tbash``` or ```tzsh```, it will start the shell from the directory defined as ```LOCAL_SRC``` in your ```.env```. It would be more convenient if it could intelligently work out if you were running multiple sites, and if you were, then ```cd``` into the directory for the site you were currently in on your host terminal.

**Comment by derschatta** [comment]
resolved by #119
