### ISSUE TITLE
'mssql' db type not supported by tdb

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#118]
```tdb``` does not support the db_type ```mssql```, despite it being a valid db type in older versions of totara. Currently if you want to run mssql, you need to specify the db type as ```sqlsvr```. We should really change it to accept either ```mssql``` OR ```sqlsvr```.

**Comment by derschatta** [comment]
Will put a patch up soon fixing this

**Comment by derschatta** [comment]
resolved by #119
