### ISSUE TITLE
totara/ is not an allowed web root for Totara 13+, needs to be totara/server/

### ISSUE THREAD

**Issue by chris-snyder-totara** [totara/totara-docker-dev#136]
Currently totara-docker-dev sites use the source code root as a web root, but this might be prevented in the future for security reasons.

The web root for Totara 13+ must be set to server/

**Comment by derschatta** [comment]
found: https://stackoverflow.com/questions/8199231/how-to-setup-mass-dynamic-virtual-hosts-in-nginx

answer no. 7 might be something we could do. Basically dynamically resolving `mysite.totara73` to the folder `/var/www/totara/src/mysite/server`. Have to try it out
