### ISSUE TITLE
Can't tbash into non-php containers

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#138]
I get the following message:
```
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "chdir to cwd (\"/var/www/totara/src\") set in config.json failed: no such file or directory": unknown
```
When I run ```tbash pgsql```
This is presumably because tbash ```cd```s into the site directory you are in in your home terminal session, but of course non-php containers don't have your site directory as a volume

**Comment by Sundayfree** [comment]
Hi i added 
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
     
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql12-data:/var/lib/postgresql/data
 into pgsql in the pgsql.yml file 
it works
