### ISSUE TITLE
Add pgsql13 container

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#158]

**Comment by samanthajayasinghe** [comment]
It's already there :) 
https://github.com/totara/totara-docker-dev/blob/master/compose/pgsql.yml#L95

**Comment by derschatta** [comment]
it still does use pgsql 12 if you use the generic container name `pgsql`. As I've noted on a different PR changing the generic container to a different versions creates problems for users who already use that container, they first have to delete the old volume and container before being able to use the new version. I vote for going away from using the generic one and just use the container with the specific version, less friction in daily use and it's clear which version you are using

**Comment by markmetcalfe** [comment]
Yeah agree that we shouldn't have generic container names. Renamed this issue to be about making the container name more consistent with how we've named the PHP ones

**Comment by markmetcalfe** [comment]
> it still does use pgsql 12 if you use the generic container name `pgsql`. As I've noted on a different PR changing the generic container to a different versions creates problems for users who already use that container, they first have to delete the old volume and container before being able to use the new version. I vote for going away from using the generic one and just use the container with the specific version, less friction in daily use and it's clear which version you are using

Created #159 for this
