### ISSUE TITLE
Specify the version in the names of the DB containers

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#159]
Currently there exists containers for our databases that don't actually define what version they are, e.g. `pgsql` (should be `pgsql12`), `mysql` (should be `mysql57`), `mariadb` (should be `mariadb105`), and `mssql` (should be `mssql2017`)
We should rename them to reflect what version they are, as otherwise it makes it more difficult when adding new containers. It also raises more awareness around what version you are actually using.

**Comment by derschatta** [comment]
Done in #250 which will be part of next release
