### ISSUE TITLE
Confusing shell aliases override behaviour

### ISSUE THREAD

**Issue by simoncoggins** [totara/totara-docker-dev#174]
I wanted to change the default email/password for the install command so I copied shell/default-aliases.sh to shell/aliases.sh. However I found that it was not getting picked up within the shell container.

Turns out that it sources all .sh files in the shell folder in alphabetical order. I didn't remove the original default-aliases.sh because it's in GIT, so that version replaced my install command. If I renamed the new file to my-aliases.sh it worked fine as it comes later alphabetically.

Not sure if there is a good fix for this or if it's just a documentation issue as it's obviously handy for the default aliases to work out of the box.

**Comment by derschatta** [comment]
@simoncoggins hopefully #254 addresses this.

**Comment by derschatta** [comment]
Merged to develop, will be released soon
