### ISSUE TITLE
Apache server drops authorization header when served over https

### ISSUE THREAD

**Issue by simoncoggins** [totara/totara-docker-dev#208]
Apparently apache's default config is to drop the authorization header for https requests for security reasons (?). See here for more information:

https://stackoverflow.com/questions/26475885/authorization-header-missing-in-php-post-request
https://stackoverflow.com/questions/37158714/enable-apache-http-authorization-header

This breaks our external API authorization when served via apache over https (e.g. when using ngrok), because the header is stripped.

Adding the following code to apache/config/remote-server.conf fixes the issue:
```
# Don't strip Authorization header
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```
probably makes sense to include this in the config by default.

**Comment by derschatta** [comment]
fixed in #227
