### ISSUE TITLE
Config.php default settings have poor performance

### ISSUE THREAD

**Issue by KevinHottinger** [totara/totara-docker-dev#211]
Currently the config.php has caching turned off for graphql schemas, this was causing noticeable performance issues on the M1 and presumably for others.

The following line should be commented out by default to enable the cache
` $CFG->cache_graphql_schema = false;`

The lang string cache should also be on by default
` $CFG->langstringcache = false;`

**Comment by derschatta** [comment]
that's actually also my preferred way to do it as I can always purge caches when changing GraphQL queries. The schema generation has a huge impact on performance. Not only on M1 Macs.

**Comment by derschatta** [comment]
The langstringcache has minimal impact on my sites performance though, maybe that could be left in

**Comment by derschatta** [comment]
fixed in #226
