### ISSUE TITLE
Selenium on M1

### ISSUE THREAD

**Issue by KevinHottinger** [totara/totara-docker-dev#212]
Currently the selenium image we use by default is not supported on  M1 macs

```
 --- Failed hooks:

    BeforeScenario # behat_hooks::before_scenario()
      Resetting of Mink session failed (Exception)
```

To get around this we found switching to a different image 'seleni**arm**' which is experimental and community supported seems to resolve this.

Switched to seleni**arm**/standalone-**chromium**:4.3.0-20220624

See the Docs here:
https://github.com/SeleniumHQ/docker-selenium#experimental-mult-arch-aarch64armhfamd64-images

Would it be possible to switch image versions based on a env variable?

**Comment by derschatta** [comment]
hm good catch. We would need to try this together I think. The alternative is to provide additional container definitions for arm in the compose files.

**Comment by benfes** [comment]
Just to add to this, I've found that seleniarm/standalone-chromium:4.3.0-20220624 - didn't work for me, however version `seleniarm/standalone-chromium:4.8.1-20230226` did work - but config.php needs to be updated with the following settings:
```php
// ...
if ($DOCKER_DEV->major_version >= 10) {
    // Behat config for Totara 10+
    $CFG->behat_profiles['default'] = array(
        'browser' => 'chrome',
        'wd_host' => "http://$DOCKER_DEV->behat_host:4444/wd/hub",
        'capabilities' => array(
            'browserName' => 'chrome',
            'browserVersion' => '110.0',
            'platform' => 'Linux',
            // 'version' => 50,
            // 'browser' => 'chrome',
            'extra_capabilities' => array(
 //...
```

Specifically `browserName`, `browserVersion`, `platform`

**Comment by benfes** [comment]
You'll also want to update the extra_capabilities to ensure chrome is matched for following session requests:
```php
// ...
'extra_capabilities' => array(
        'alwaysMatch' => array(
                'browserName' => 'chrome',
        ),
// ...
```

**Comment by derschatta** [comment]
> You'll also want to update the extra_capabilities to ensure chrome is matched for following session requests:
> 
> ```
> // ...
> 'extra_capabilities' => array(
>         'alwaysMatch' => array(
>                 'browserName' => 'chrome',
>         ),
> // ...
> ```

If the capabilities 'browserName', 'browserVersion' and 'platform' is set correctly I don't think this is necessary. At least in my tests I did not need it.
