### ISSUE TITLE
Two different default versions of postgres versions

### ISSUE THREAD

**Issue by KevinHottinger** [totara/totara-docker-dev#213]
In config.php we have set it to version 14
/** PostgresSQL */
$CFG->dbhost = 'pgsql14'; // See https://github.com/totara/totara-docker-dev/wiki/Database%20Credentials for other versions

In .env.dist we have set it to version 13
DEFAULT_CONTAINERS=nginx,pgsql13,php

**Comment by derschatta** [comment]
good catch @KevinHottinger 

I think we should go for 13 as it's supported on more Totara versions out-of-the-box

**Comment by derschatta** [comment]
fixed in #224
