### ISSUE TITLE
Expose Machine Learning Service config options to .env file

### ISSUE THREAD

**Issue by codyfinegan** [totara/totara-docker-dev#228]
**Is your feature request related to a problem? Please describe.**
Currently the only way to configure the custom machine learning options in ml-service is to edit the .yml file directly.

**Describe the solution you'd like**
The ML-specific environment options should be exposed to .env like the ML_TOTARA_KEY option is, so all settings can be configured with a .env change & a service restart.

**Comment by derschatta** [comment]
done in #229
