### ISSUE TITLE
Arm support in Docker images

### ISSUE THREAD

**Issue by jonnybarnes** [totara/totara-docker-dev#231]
**Is your feature request related to a problem? Please describe.**
It would improve performance when developing on an Apple Silicon powered Mac if there were ARM versions if the various Docker images as well as the current AMD versions.

This is definitely something that Laravel Sail supports for its docker images. If you look at one of the images you see there are two digests: https://hub.docker.com/r/laravelsail/php81-composer/tags

I wonder if its something I could do myself if I built the docker images locally? (Sorry still new to all this Docker stuff)

**Comment by derschatta** [comment]
I was able to build and push images up following these instructions: https://medium.com/geekculture/docker-build-with-mac-m1-d668c802ab96

I've built two test images:
* totara/docker-dev-nginx:multiarch
* totara/docker-dev-php74:multiarch

These need to be tested on a Mac with M1 or M2 chip. If they work I can see how we can create these images automatically.

The easiest way would be to create an arm.yml file under /custom/:

```
version: "3.7"
services:

  nginx:
    image: totara/docker-dev-nginx:multiarch

  php-7.4:
    image: totara/docker-dev-php74:multiarch
```

and `tup` the php container. The postgres image, e.g. pgsql14, should already have multiarch support.

@benfes @Kunleodusan Could you try this out for me and see if the images work and whether there's any difference in performance?

**Comment by derschatta** [comment]
Also noting that the Mssql server 2017 and 2019 is not available for ARM so we'd have to stick with the AMD64 ones for now. Will check out the 2022 version though. We do not yet support it but it would be interesting to see if Totara runs on it.

**Comment by derschatta** [comment]
Created some docs: https://github.com/totara/totara-docker-dev/wiki/Docker-dev-on-Mac-with-ARM-chip-(M1---M2)

**Comment by derschatta** [comment]
@jonnybarnes if you want to give this a try go for it and let us know if it works and whether there's an improvement.

**Comment by derschatta** [comment]
patch merged into develop. Can already be used by following the instructions on the wiki page. Closing.

**Comment by jonnybarnes** [comment]
This works! Thanks

I don’t have hard numbers, but it feels quicker with dev mode tuned off in the `config.php`, it feels just as slow with dev mode turned on though 🐌
