### ISSUE TITLE
Restrict access to some directories and files create continues error in SCORM activities

### ISSUE THREAD

**Issue by angelakuznetsova** [totara/totara-docker-dev#232]
In server configuration files, we have some code to restrict access to files and directories while using ngrok. 
If you are restricting access the SCROM activities not working properly.

**To Reproduce**
1. Create a cource
2. Create a SCORM activity and add SCORM to it
3. Try to run SCROM module. 
4. You will see persistent errors

**Expected behavior**
Should work without interrupting. 

**Screenshots**
![Screenshot 2022-12-13 at 15 15 36](https://user-images.githubusercontent.com/120606574/207741152-9e0ff2b7-c637-4e6e-9356-f05f1d68f2ca.jpg)

![Screenshot 2022-12-13 at 15 21 11](https://user-images.githubusercontent.com/120606574/207741191-7d6d97a8-d8f9-4ef8-8a85-36b8bfcbe7ae.jpg)

Causing: 
Forbidden access to .txt file, particularly to checknet.txt
We need to edit the regex expression to allow access to checknet.txt

location ~ .*\.(txt|md|json|xml|mustache)$ {
    deny all;
}

**Comment by derschatta** [comment]
Current workaround:

Add the following to nginx/config/remote-server.conf

```
# Allow this one specifically to make sure SCORM network checks are successful
location server/lib/yui/build/moodle-core-checknet/assets/checknet.txt {
    allow all;
}
```

**Comment by derschatta** [comment]
PR is merged
