### ISSUE TITLE
Update selenium & chrome images

### ISSUE THREAD

**Issue by marsh0lion** [totara/totara-docker-dev#234]
The selenium and chrome images are considerably out of date and could do with updating.

Selenium is still running 3.141.59 (latest is 4.7.2, Jenkins is running 4.4.0), The chrome node is also considerably out of date (Jenkins is running selenium/node-chrome:102.0 - 103 & above currently has a date issue with Totara forms).

When running behat on Totara 9 (& below), the chrome node needs to be running chrome 72 (or below) and as result, the hub needs to be running selenium 3.

**Comment by derschatta** [comment]
will be fixed by #246
