### ISSUE TITLE
Error 'multiarch-support is not installed' during php container build

### ISSUE THREAD

**Issue by simoncoggins** [totara/totara-docker-dev#237]
**Describe the bug**

While trying to create a local build of the PHP8.0 container I received the following error:

```
#0 0.504 2023-03-21 22:27:58 (21.7 MB/s) - ‘libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb’ saved [1048576/1048576]
#0 0.504
#0 0.547 Selecting previously unselected package libssl1.0.0:amd64.
#0 0.547 dpkg: regarding .../libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb containing libssl1.0.0:amd64, pre-dependency problem:
#0 0.547  libssl1.0.0 pre-depends on multiarch-support
#0 0.547   multiarch-support is not installed.
#0 0.547
#0 0.547 dpkg: error processing archive ./libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb (--install):
#0 0.547  pre-dependency problem - not installing libssl1.0.0:amd64
#0 0.559 Errors were encountered while processing:
#0 0.559  ./libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb
```

I found a previous post about this problem, and while it didn't work unchanged I was able to get it working again by updating the change to account for changes in the debian repo folder. The diff of the change that worked was:
```
diff --git a/php/php80/Dockerfile b/php/php80/Dockerfile
index 2ba777c..7248252 100644
--- a/php/php80/Dockerfile
+++ b/php/php80/Dockerfile
@@ -83,6 +83,10 @@ RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
     mssql-tools \
     unixodbc-dev

+# Workaround to avoid an ODBC PreDepend error about multi-arch support that is not installable
+RUN wget "http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/multiarch-support_2.27-3ubuntu1.6_amd64.deb" \
+    && DEBIAN_FRONTEND=noninteractive dpkg -i ./multiarch-support_2.27-3ubuntu1.6_amd64.deb
+
 # Workaround to get MSSQL connection working on Debian 10 (buster)
 # https://emacstragic.net/2017/11/06/mssql-odbc-client-on-debian-9-stretch/
 RUN wget "http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb" \
```

In theory this same problem will affect the repository next time we try to build pre-built packages so should be fixed in code.

Note that the above patch only fixes for php8.0 - need to work out which versions need this change and if the specific version is appropriate for all builds. You can see the available packages in the folder via the web:
http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/

Noting also that they seem to remove older versions periodically so this hardcoded approach might break at some point. Not sure if there is a better way to add this dependency that will be more robust?

**Comment by derschatta** [comment]
#244 removed the dependency on that debian libssl package.
