### ISSUE TITLE
Outdated database credential docs

### ISSUE THREAD

**Issue by jonnybarnes** [totara/totara-docker-dev#259]
The wiki page here: https://github.com/totara/totara-docker-dev/wiki/Database%20Credentials

Only shows up to PostgreSQL 14

Whereas the actual project now supports up to PostgreSQL 15: https://github.com/totara/totara-docker-dev/blob/f0eeff71ba18b3e0a62523b09545b6fb3fa1cf37/compose/pgsql.yml#L133

**Comment by derschatta** [comment]
Thanks @jonnybarnes . I've updated the page.
