### ISSUE TITLE
New DB docker images

### ISSUE THREAD

**Issue by angelakuznetsova** [totara/totara-docker-dev#261]
We need to add DB docker images:

Postgres 16.1

MySQL 8.2

MariaDB 11.0. 11.1, 11.2

MSSQL Server 2022

**Comment by codyfinegan** [comment]
Will add postgres 16 & MySQL 8.2

MariaDB we'll leave as those are unsupported. MSSQL TBD

**Comment by codyfinegan** [comment]
Update, MySQL 8.4 & MariaDB 11.4 over the named ones above
