### ISSUE TITLE
Apache container fails to expose Totara repository folders containing hyphen (-) in the name

### ISSUE THREAD

**Issue by florentplomb** [totara/totara-docker-dev#286]
**Describe the bug**
Apache container fails to expose Totara repository folders when the folder name contains a '-' (hyphen).

**To Reproduce**

Change the name of one of the Totara repositories in your LOCAL_SRC to include a hyphen, e.g.,
"/home/totara/totara-sites/test-totara"

Run the following commands:
1. tup
2. tstop nginx (go to the URL -> it works, the repository is exposed)
3. tup apache (go to the same URL -> 404 error)

**Expected behavior**
Apache should behave the same way as Nginx, exposing the repository even if the folder name contains a hyphen.

**Desktop**
OS: Windows 11 - WSL 2 - Ubuntu 22.04.3 LTS
**Additional context**
The repository is present in the Apache container under /var/www/totara/src/test-totara, but it fails to be exposed when accessed via the web browser.

**Comment by derschatta** [comment]
Thanks for reporting this @florentplomb and apologies for the time it took to get to it.

We've addressed it in the codebase and pushed the new image up to docker hub.

You can pull the image again `docker pull totara/docker-dev-apache` and recreate it with `tup apache`. This should fix it.
