### ISSUE TITLE
php-7.4-debug container is installing the wrong php version

### ISSUE THREAD

**Issue by ivanange** [totara/totara-docker-dev#288]
**Describe the bug**
The image corresponding to php7.4 debug (```totara/docker-dev-php74-debug:multiarch```) has a defect. Checking the image's code it's installing php7.3 instead of 7.4
![Screenshot 2024-11-06 at 22 39 49](https://github.com/user-attachments/assets/7a0aa013-220f-4a18-94d4-ab7cf8a1433c)

**To Reproduce**
1. Install the totara-docker)dev tool normally on Mac (with silicon chip
2. ```tup php-7.4```
3. ```tzsh php-7.4-debug```
4. In the new shell ```php -v```
5. You get 7.3 instead of PHP 7.4

**Expected behavior**
I should have PHP 7.4 running in this container as in the normal php-7.4 container

**Desktop (please complete the following information):**
 - OS: [Mac OS M*]

**Comment by derschatta** [comment]
Thanks @ivanange for reporting this. We've rebuilt the image and pushed it up to docker hub.
You'd need re-pull the image with `docker pull totara/docker-dev-php74:multiarch`.

Hope this helps.

**Comment by derschatta** [comment]
ah ignore this please, I realised it's the debug image you have issues with. I'll make sure we update all of those. Will let you know.

**Comment by derschatta** [comment]
ok that's all addressed. I suggest pulling all related php 7.4 images again:

```
docker pull totara/docker-dev-php74:multiarch
docker pull totara/docker-dev-php74-debug:multiarch
docker pull totara/docker-dev-php74-cron:multiarch
```

**Comment by ivanange** [comment]
Thanks, I tested and it works!
