### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by simoncoggins** [totara/totara-docker-dev#31]
* Add section on how to update containers after pulling new changes from this repo
* Add details to Running Behat section
** Need to run 'tup selenium-hub' before running behat
** Need to point to selenium-hub in config.php
* Include dynamic wwwroot for config.php to allow access via totaraXX, totaraXX.debug and totaraXX.behat simultaneously

**Comment by markmetcalfe** [comment]
Should also document how to connect to the php containers via VNC for debugging behat

**Comment by markmetcalfe** [comment]
Done as part of #164 and #165
