### ISSUE TITLE
Behat tests with javascript fail due to $_COOKIE['BEHAT'] not set

### ISSUE THREAD

**Issue by barryo-learningpool** [totara/totara-docker-dev#51]
**Describe the bug**
Behat tests containing @javascript tags fail due to $_COOKIE['BEHAT'] not set

**To Reproduce**
1. Setup Totara 11 to run on mysql / mariadb using PHP 7.2 / 7.3
2. Add additional parameters for behat to config.php e.g. 
`$CFG->behat_wwwroot = 'http://totara72.behat';
$CFG->behat_dataroot = '/var/www/totara/data/ver10.mysql.behat';
$CFG->behat_prefix = 'behat_';`
3. Start up containers e.g. `bin/tup mariadb php-7.3 selenium-hub` `bin/tup` mysql php-7.2 selenium-hub`
4. Log into php container and run the behat init.php script
5. Run a behat test containing an @javascript tag e.g. `vendor/bin/behat --tags="@block_accessibility"`
6. Visit http://totara72.behat or http://totara73.behat in the browser

**Expected behavior**
The behat test should execute when it contains javascript tags
The acceptance test site should be accessible through the browser

**Actual behaviour**
The behat test fails with:

```
 Failed hooks:

   BeforeScenario # behat_hooks::before_scenario()
   Visiting of the main page failed (Exception)
```
The acceptance test site is not accessible through the browser. The user is redirected to the http://totara72or http://totara73 site (due to empty($_COOKIE['BEHAT']) ).

**Screenshots**
<img width="623" alt="Screen Shot 2019-05-10 at 11 25 44" src="https://user-images.githubusercontent.com/28761622/57520945-d914bb00-7316-11e9-98da-3cd3e87c3618.png">

**Desktop (please complete the following information):**
 - OS: MAC OS High Sierra 10.3.6
 - Browser: Chrome
 - Version: 73.0.3683.103 (Official Build) (64-bit)

**Additional context**

1. When visiting http://totara72.behat or http://totara73.behat in the browser it redirects to http://totara72 or http://totara73
2. I can access the Selenium console ok in http://totara72.behat:4444/ and http://totara73.behat:4444/
3. It seems as though Totara is redirecting to $CFG->wwwroot because it thinks its not a behat test site i.e. behat_is_test_site() in lib/setup.php returns false because $_COOKIE['BEHAT'] is empty.

**Comment by derschatta** [comment]
Hi @barryo-learningpool,

how does your behat.yml look like? Does it have this?

```
    Behat\MinkExtension:
      base_url: 'http://totara72.behat'
      goutte: null
      selenium2:
        wd_host: 'http://selenium-hub:4444/wd/hub'
        ...
```

You cannot open the behat page by visiting http://totara72.behat directly, it will always redirect you. This is expected behaviour.

I add this in my config.php so that the behat.yml is correctly built if you run `php admin/tool/behat/cli/init.php`

```
$CFG->behat_wwwroot = 'http://totara72.behat';
$CFG->behat_dataroot = '/var/www/totara/data/ver13.pgsql.behat';
$CFG->behat_prefix = 'bht_';

$CFG->behat_config = array(
    'default' => array(
        'extensions' => array(
            'Behat\MinkExtension\Extension' => array(
                'browser_name' => 'chrome',
                'default_session' => 'selenium2',
                'selenium2' => array(
                    'browser' => 'chrome',
                    'wd_host' => 'http://selenium-hub:4444/wd/hub',
                    'capabilities' => array(
                        "browser" => "chrome",
                        "browserName" => "chrome",
                        "browserVersion" => "",
                        "version" => '',
                        'platform' => 'LINUX'
                    )
                )
            )
        )
    ),
);
```

Please check your behat.yml file, it's probably the key to your problem.

**Comment by barryo-learningpool** [comment]
Hi @derschatta, 

I was trying to override it in behat_local.yml but didn't quite get it right.

'wd_host' => 'http://selenium-hub:4444/wd/hub', is what I was missing. Thanks for the help
