### ISSUE TITLE
Add container for PHP 5.3

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#70]
Early Totara 2.x versions have a minimum php version of 5.3, so it would be good to have a container for it

**Comment by derschatta** [comment]
started to create a Dockerfile, building PHP 5.3 from Source (similar as with 5.4)

**Comment by derschatta** [comment]
see #71  it's WIP
getting this error:
```
/usr/lib/x86_64-linux-gnu/libc-client.a(osdep.o): In function `ssl_onceonlyinit.part.8':
(.text+0x641e): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: ext/intl/msgformat/msgformat_helpers.o: undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:279: recipe for target 'sapi/fpm/php-fpm' failed
make: *** [sapi/fpm/php-fpm] Error 1
```

**Comment by derschatta** [comment]
@markmetcalfe @samanthajayasinghe  I got PHP 5.3 working last night, pushed up the patch in #71 .

This also changes 5.4 and 5.5 to inherit the same base image.

I am now using [phpbrew](https://github.com/phpbrew/phpbrew) to build and install the PHP versions, at least for 5.3 to 5.5

The only thing still not 100% working is MSSQL support. Extension is installed and shows up properly on phpinfo() and also a test connection can succesfully be made but still the page gives me a DB error. Will investigate when I find time.

Would be great if you find time to review the changes, it's still a draft PR.

**Comment by derschatta** [comment]
Done in #71
