### ISSUE TITLE
Xdebug with PHP 7.3 not working

### ISSUE THREAD

**Issue by derschatta** [totara/totara-docker-dev#9]
**Describe the bug**
When trying to open Totara with PHP 7.3 and xdebug the PHP 7.3 fpm backend just terminates. 

**To Reproduce**
1. Point nginx to 'php-7.3-debug'
2. Try to open a page
3. See a 503 error
4. See something like `WARNING: [pool www] child 10 exited on signal 11 (SIGSEGV) after 45.864850 seconds from start` in the logs

**Expected behavior**
xdebug works

**Additional context**
I think PHP 7.3 with xdebug 2.7.0beta1 is still unstable and not working. For now I changed the nginx backend for totara73 to the one without xdebug to be able to open the site.

**Comment by shenron** [comment]
I'm not using totara-docker-dev, but I have the same bug between PHP 7.3 and xdebug 2.7.0beta1. Add this config to php.ini fix my problem:

> opcache.optimization_level=0x7FFFBBFF

Source: https://bugs.xdebug.org/view.php?id=1583

I hope this can help you.

**Comment by derschatta** [comment]
Thanks @shenron! We will try that. On the CLI debugging does work without any problems.

**Comment by derschatta** [comment]
fixed in #25
