### ISSUE TITLE
'tnpm' command does not work with sites in sub-directories on macOS

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#90]
**Describe the bug**
The `tnpm` command was made with the intention of supporting a docker setup that has multiple sites installed in different sub-directories. When `tnpm` is run while in a sub-directory it will run the command in the corresponding sub-directory inside the node container. This works fine on linux, but it was not tested on macOS and it does not work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run an npm command with `tnpm` while in a site installed in a subdirectory - e.g. `tnpm run tui-dev`
2. You will get an npm error like this: `enoent ENOENT: no such file or directory, open '/var/www/totara/src/package.json'`, complaining there is no package.json, because it did not correctly `cd` into the appropriate subdirectory.

**Expected behaviour**
The command should be run in the appropriate folder without error.

**Comment by simoncoggins** [comment]
Just noting that this does work for me on MacOS with v1.1.2:
```
$ pwd
/Users/simonc/code/totara/main
$ tnpm run tui-dev

> totaralms@ tui-dev /var/www/totara/src/main
> webpack --mode development

Child modern:
       1186 modules
Child legacy:
       1006 modules
Child scss-to-scss:
       456 modules
```
my src folder is /Users/simonc/code/totara, main is a subfolder containing an install's wwwroot.
